### ISSUE TITLE
所以这东西到底有没有用

### ISSUE THREAD

**Issue by tetsaicn** [LoliLin/Uptime-Page#1]
完事以后就生成了个index文件，里面完全是空的，一点数据都没有
config配置过了，apikey啥的确认过绝对没问题，也没动过别的，刷新也没报过错

**Comment by LynMoe** [comment]
能否附上php的错误日志？

**Comment by tetsaicn** [comment]
`刷新也没报过错`  没有错误日志。。。。。也检查过nginx日志等

渲染以后是这样的： http://142.93.28.155/
只有一个All systems are operational.

**Comment by LynMoe** [comment]
哦对了忘记说了，监控项的名称要满足 「名称/分类名/分类排序」

**Comment by tetsaicn** [comment]
ok tks
